### ISSUE TITLE
 basic_string::substr

### ISSUE THREAD

**Issue by Tengjun0520** [Zilong-Li/BaseVarC#4]
Hi,Zilong-Li

I have a issue. I always get an error when running

ERROR: something wrong when quering the reads in bam/161302.sorted.markdup.bam basic_string::substr: __pos (which is 161) > this->size() (which is 150)

Thanks

**Comment by Zilong-Li** [comment]
Hey,

Thanks for using BaseVarC. 

Yeah, I've noticed there is an out_of_range exception bug as I commented here [https://github.com/Zilong-Li/BaseVarC/issues/3#issuecomment-600523788](https://github.com/Zilong-Li/BaseVarC/issues/3#issuecomment-600523788). Could you share your bam with me? It will help me find the bug quickly. And I am currently occupied with other things, so I may be slow to reply.

Best

**Comment by Tengjun0520** [comment]
你好，


我的bam文件在附件中，这个bam文件是经过去除PCR重复、重比对和碱基质量校正得到的。我用GATK call snp 是没有问题的。


谢谢
















At 2020-07-08 17:03:15, "Zilong-Li" <notifications@github.com> wrote:

Hey,

Thanks for using BaseVarC.

Yeah, I've noticed there is an out_of_range exception bug as I commented here #3 (comment). Could you share your bam with me? It will help me find the bug quickly. And I am currently occupied with other things, so I may be slow to reply.

Best

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的云附件
470694_recal.bam (2.24G, 2020年7月23日 20:36 到期)
下载

**Comment by Zilong-Li** [comment]
你好，你能不能把bam裁剪一下，只保留哪个有报错的区域？这么大的文件我无法接收。



Tengjun0520 <notifications@github.com> 于2020年7月8日周三 下午8:53写道：

> 你好，
>
>
> 我的bam文件在附件中，这个bam文件是经过去除PCR重复、重比对和碱基质量校正得到的。我用GATK call snp 是没有问题的。
>
>
> 谢谢
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>

**Comment by Zilong-Li** [comment]
@Tengjun0520  fixed. see [commit b76f88](https://github.com/Zilong-Li/BaseVarC/commit/b76f88df614232f7ee9f562dfcd0488c12e80e61)
